---
- name: "Set Time Zone to {{ timezone }}"
  timezone:
    name: "{{ timezone }}"

- name: Copy user settings to /home/azureuser
  copy: src=files/home/{{ item }} dest=/home/azureuser/ owner=azureuser group=azureuser mode=0644
  with_items:
   - ".bash_aliases"
   - ".bashrc"
   - ".htoprc"
   - ".screenrc"

- name: Copy user settings to /root
  copy: src=files/home/{{ item }} dest=/root/ owner=root group=root mode=0644
  with_items:
   - ".bash_aliases"
   - ".bashrc"
   - ".htoprc"
   - ".screenrc"

- name: Copy issues.net /etc
  copy: src=files/etc/{{ item }} dest=/etc/ owner=root group=root mode=0644
  with_items:
   - "issue.net"

- name: Ensures sshd_config.d exists
  file: path=/etc/ssh/sshd_config.d mode=755 state=directory
  notify:
    - reload sshd
  tags: [ 'ssh' ]

- name: Copy custom sshd_config /etc/ssh
  copy: src=files/etc/ssh/sshd_config.d/custom.conf dest=/etc/ssh/sshd_config.d owner=root group=root mode=0600
  notify:
    - reload sshd
  tags: [ 'ssh' ]

- name: Configure journald
  copy: src=files/etc/systemd/journald.conf dest=/etc/systemd/ owner=root group=root mode=0644
  notify:
    - reload journald
  tags: [ 'journald' ]

- name: "Install dependencies"
  tags: [ 'system', 'tools' ]
  apt:
    pkg:
      - apt-listchanges
      - apt-transport-https
      - bzip2
      - btop
      - cron
      - chrony
      - curl
      - debian-goodies
      - git-core
      - htop
      - iftop
      - iotop
      - iperf3
      - iptraf
      - less
      - lm-sensors
      - mailutils
      - moreutils
      - mtr
      - needrestart
      - ripgrep
      - rkhunter
      - rsyslog
      - screen
      - smartmontools
      - snmp
      - software-properties-common
      - sudo
      - sysfsutils
      - sysstat
      - vim-nox
    state: present

- name: Run apt-get update
  cron:
    name: "Ubuntu Repository Update"
    minute: 0
    hour: 12
    user: root
    job: "/usr/bin/apt-get update"

- name: Run apt-get upgrade
  cron:
    name: "Linux Upgrade"
    minute: 0
    hour: 21
    user: root
    job: "/usr/bin/apt-get -y upgrade"

- name: Run apt-get autoremove
  cron:
    name: "Package Auto Remove"
    minute: 45
    hour: 22
    user: root
    job: "/usr/bin/apt-get -y autoremove && /usr/bin/apt-get -y purge $(dpkg --list |grep '^rc' |awk '{print $2}')"

- name: Run apt-get autoclean
  cron:
    name: "Package Auto Clean"
    minute: 45
    hour: 23
    user: root
    job: "/usr/bin/apt-get autoclean"

