---
- name: Checkout benchmark repository
  ansible.builtin.git:
    repo: "{{ git_repo_benchmark }}"
    dest: /home/azureuser/opennms-benchmark
  tags: [ "project" ]

- name: Checkout ansible opennms repository
  ansible.builtin.git:
    repo: "{{ git_repo_ansible_opennms }}"
    dest: /home/azureuser/ansible-opennms
  tags: [ "project" ]
